### PR TITLE
fix: change os.homedir to node-homedir

### PR DESCRIPTION
**Pull request by limerickgds**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change
change os.homedir to node-homedir

### CODE REVIEW

**Comment by limerickgds** [comment]
@atian25

**Review by atian25 — APPROVED** [review]

**Comment by atian25** [comment]
+1

**Comment by limerickgds** [comment]
@atian25

**Comment by atian25** [comment]
喔喔... 被淹没了

**Comment by atian25** [comment]
@fengmk2 你看下然后发个版本？我好像没 npm 权限。

**Comment by JacksonTian** [comment]
真的有必要？

**Comment by atian25** [comment]
@JacksonTian 这个 node-homedir 是 @ngot 当时为解决 os.home 兼容性搞的吧

**Comment by ngot** [comment]
这里是为了解决什么问题？

**Comment by JacksonTian** [comment]
尽量在外层设定好 user 。

**Comment by limerickgds** [comment]
@ngot user 切换的问题。不过也可以从 config 拿到 appInfo.root 来解决。

**Review by fengmk2 — APPROVED** [review]

**Comment by fengmk2** [comment]
准备合并

**Comment by fengmk2** [comment]
1.1.2

**Comment by fengmk2** [comment]
pick to master 907d2c79db27580ce6d11e95c992390483d90218

**Pull request merged**
